# Site settings
title: Amirhossein Afsharrad
email: afsharrad@stanford.edu
description: PhD Candidate in Electrical Engineering at Stanford University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amirafsharrad.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Sidebar info (for Minimal theme)
logo: /assets/amirhossein.png
show_downloads: false

# Navigation
header_pages:
  - index.md
  # - research.md
  # - teaching.md
  # - blog.md

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
