# Site settings
title: Amirhossein Afsharrad
email: afsharrad@stanford.edu
description: PhD Candidate in Electrical Engineering at Stanford University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amirafsharrad.github.io" # the base hostname & protocol for your site

# Google Analytics
google_analytics: G-WCZCMVFCPD

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - index.md
  - blog.md

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
