# Site settings
title: Amirhossein Afsharrad
email: afsharrad@stanford.edu
description: "EE PhD Candidate<br>Stanford University"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amirafsharrad.github.io" # the base hostname & protocol for your site

# Google Analytics
google_analytics: G-WCZCMVFCPD

# SEO settings
author:
  name: Amirhossein Afsharrad
  email: afsharrad@stanford.edu

social:
  name: Amirhossein Afsharrad
  links:
    - https://github.com/amirafsharrad
    - https://www.linkedin.com/in/afsharrad/
    - https://scholar.google.com/citations?user=yuvhn2oAAAAJ

lang: en_US
tagline: "PhD Candidate in Electrical Engineering at Stanford University"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - research.md
  - teaching.md
  - cv.md
  - blog.md

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:title/
  teaching:
    output: true
    permalink: /teaching/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
